# Generated by Django 3.1.5 on 2021-01-12 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('ssn', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=40)),
                ('lname', models.CharField(max_length=40)),
                ('minit', models.IntegerField()),
                ('bdate', models.DateField(blank=True, null=True)),
                ('address', models.CharField(max_length=250)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('salary', models.IntegerField()),
                ('dno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.department')),
                ('super_ssn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee')),
            ],
            options={
                'verbose_name_plural': 'Employee',
            },
        ),
    ]
