# Generated by Django 3.1.4 on 2021-01-17 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMPLOYEE',
            fields=[
                ('Fname', models.CharField(max_length=10)),
                ('Minit', models.CharField(max_length=10)),
                ('Lname', models.CharField(max_length=10)),
                ('Bdate', models.DateField()),
                ('Address', models.CharField(max_length=100)),
                ('Sex', models.CharField(max_length=10)),
                ('Salary', models.IntegerField()),
                ('ssn', models.AutoField(primary_key=True, serialize=False)),
                ('Dno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Department.department')),
                ('Super_ssn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.employee')),
            ],
        ),
    ]
