# Generated by Django 3.1.4 on 2021-01-17 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PROJECT',
            fields=[
                ('Pname', models.CharField(max_length=10)),
                ('Pnumber', models.AutoField(primary_key=True, serialize=False)),
                ('Plocation', models.CharField(max_length=10)),
                ('Dnum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Department.department')),
            ],
        ),
    ]
