# Generated by Django 3.1.5 on 2021-01-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DependentName',
            fields=[
                ('dependent_name', models.CharField(default='dependant', max_length=250, primary_key=True, serialize=False)),
                ('sex', models.CharField(max_length=250)),
                ('bdate', models.DateField(blank=True, null=True)),
                ('relationship', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Dependent Name',
            },
        ),
    ]
