# Generated by Django 3.1.5 on 2021-01-12 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('dependent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependentname',
            name='essn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
    ]
