# Generated by Django 3.1.4 on 2021-01-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DEPARTMENT',
            fields=[
                ('Dname', models.CharField(max_length=20)),
                ('Mgr_start_date', models.DateField()),
                ('Dnumber', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
