# Generated by Django 3.1.5 on 2021-01-12 16:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dnumber', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=250)),
                ('mgr_start_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Department',
            },
        ),
    ]
