# Generated by Django 3.1.4 on 2021-01-17 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Department', '0001_initial'),
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='Mgr_ssn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.employee'),
        ),
    ]
