# Generated by Django 3.1.5 on 2021-01-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_department_mgr_ssn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='Mgr_start_date',
            field=models.DateTimeField(),
        ),
    ]
